name: Performance

on: [pull_request]

jobs:
  perf:
    runs-on: Ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Benchmark
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          export PATH="$SWIFTENV_ROOT/bin:$PATH"
          eval "$(swiftenv init -)"
          make bootstrap
          make perf-tester
          node ci/perf-tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
