name: Run unit tests
on: [push, pull_request]
jobs:
  test:
    name: Build and Test
    strategy:
      matrix:
        os: [macOS-10.15, Ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Test
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          export PATH="$SWIFTENV_ROOT/bin:$PATH"
          eval "$(swiftenv init -)"
          ./scripts/install-toolchain.sh
          make bootstrap
          make test
